openapi: 3.0.1
info:
  title: jsonToJson
  description: API Definition of jsonToJson
  version: 1.0.0
servers:
- url: http://localhost:8290/format
paths:
  /:
    get:
      responses:
        default:
          description: Default response
    post:
      responses:
        default:
          description: Default response
